_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("syntext1_poly_train", "syntext2_poly_train","syntext800K_poly_train") #  "totaltext_poly_train_pos", ,"mlt_poly_train","syntext1_poly_train", "syntext2_poly_train","syntext800K_poly_train"
  TEST: ("totaltext_poly_test",)

MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  LABELENCODER:
    WEIGHT: "pretrained_models/epoch=99-step=196000_latest.ckpt"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (300000,)
  MAX_ITER: 600000
  CHECKPOINT_PERIOD: 10000

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: "output/r_50_poly/pretrain"